# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce03337983e4a5285983691e84b42f218db4e73fe4965d5acbcb2066806cbdd1295a496f8d4b36af5a437b6cf33aa9e7f1e8a21eccf6fc43c92ac7a45914d5df

test:
  secret_key_base: 565db3a89a78026732708c89fbb8cfca07d1208bf5630e36c515aa121ec4c5ae66008f280554b0d99a6b1d8da6d358bed1ec5d94f28d77d3c712bc252d8e47d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
